GestionMusiques/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^musiques/',include ('musiques.urls')),
]

musiques/urls.py
from django.conf.urls import url, include
from .views import *
from . import views
from django.views.generic import TemplateView

app_name = 'musiques'

urlpatterns = [
    url(r'^modifMorceau/(?P<pk>\d+)$', views.URLUpdate.as_view(), name='url_updateM'),
    url(r'^modifArtiste/(?P<pk>\d+)$', views.URLUpdateA.as_view(), name='url_updateA'),
    url(r'^SupprMorceau/(?P<pk>\d+)$', views.URLDelete.as_view(), name='url_deleteM'),
    url(r'^SupprArtiste/(?P<pk>\d+)$', views.URLDeleteA.as_view(), name='url_deleteA'),
    url(r'^ajoutMorceau/$', views.URLCreate.as_view(), name='url_createM'),
    url(r'^ajoutArtiste/$', views.URLCreateA.as_view(), name='url_createA'),
    url(r'^base/$', views.Base_View, name='url_base'),
    url(r'^Artistes/$', views.artiste_View, name='url_artistes'),
]

musiques/models.py
from django.db import models

# Create your models here.
class Artiste(models.Model):
    nom = models.CharField(max_length=64)

    def __str__(self):
        return '{self.nom}'.format(self=self)

class Morceau(models.Model):
    # artiste = models.CharField(max_length=64)
    titre = models.CharField(max_length=64)
    date_sortie = models.DateField(null=True)
    clefE = models.ForeignKey(Artiste, null=True)

    def __str__(self):
        return '{self.titre}'.format(self=self)

musiques/views.py
from django.shortcuts import render, get_object_or_404
from django .http import HttpResponse
from .models import *
from django.views.generic import DetailView, UpdateView, CreateView, DeleteView
from .form import *
from django.core.urlresolvers import reverse_lazy

class MorceauDetailView(DetailView):
    model = Morceau

class URLUpdate(UpdateView):
    model = Morceau
    template_name = 'musiques/Modif.html'
    form_class = MorceauForm
    success_url = '/musiques/base/'

class URLUpdateA(UpdateView):
    model = Artiste
    template_name = 'musiques/Modif.html'
    form_class = ArtisteForm
    success_url = '/musiques/base/'

class URLCreate(CreateView):
    model = Morceau
    template_name = 'musiques/Ajout.html'
    form_class = MorceauForm
    success_url = '/musiques/base/'

class URLCreateA(CreateView):
    model = Artiste
    template_name = 'musiques/Ajout.html'
    form_class = ArtisteForm
    success_url = '/musiques/base/'

class URLDelete(DeleteView):
    model = Morceau
    template_name = 'musiques/Suppr.html'
    context_object_name = "donnees"
    form_class = MorceauForm
    success_url = '/musiques/base/'
    def get_object(self, queryset=None):
        code = self.kwargs.get('pk', None)
        return get_object_or_404(Morceau, id=code)

class URLDeleteA(DeleteView):
    model = Artiste
    template_name = 'musiques/SupprA.html'
    context_object_name = "donnees"
    form_class = ArtisteForm
    success_url = '/musiques/base/'
    def get_object(self, queryset=None):
        code = self.kwargs.get('pk', None)
        return get_object_or_404(Artiste, id=code)


# Create your views here.
def morceau_detail(request, pk):
    return HttpResponse('OK')

def Base_View(request):
    morceaux = Morceau.objects.all()
    return render(request,"musiques/Base_View.html", {"morceaux":morceaux})

def artiste_View(request):
    artistes = Artiste.objects.all()
    return render(request,"musiques/Artistes.html", {"artistes":artistes})

musiques/templates/musiques/Ajout.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Django Musique</title>
    <link rel="stylesheet" href="../../static/css/bootstrap-theme.css">
    <link rel="stylesheet" href="../../static/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="../../static/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/css/index.css">
</head>
<body>
  <hr>
  <nav class="listeBoutons">
    <a href="{% url 'musiques:url_createM' %}"><button type="submit">Ajouter un Morceau</button></a>
    <a href="{% url 'musiques:url_createA' %}"><button type="submit">Ajouter un Artiste</button></a>
    <a href="{% url 'musiques:url_artistes' %}"><button type="submit">Tous les artistes</button></a>
    <a href="{% url 'musiques:url_base' %}"><button type="submit">Tous les morceaux</button></a>
  </nav>
  <hr>
  <main class="corps">
    <section>
      <h3>Ajouter</h3>
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
      <input type="submit" value="Ajouter" />
      </form>
    </section>

  </main>
</body>

musiques/templates/musiques/Artistes.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Django Musique</title>
    <link rel="stylesheet" href="../../static/css/bootstrap-theme.css">
    <link rel="stylesheet" href="../../static/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="../../static/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/css/index.css">
</head>
<body>
  <hr>
  <nav class="listeBoutons">
    <a href="{% url 'musiques:url_createM' %}"><button type="submit">Ajouter un Morceau</button></a>
    <a href="{% url 'musiques:url_createA' %}"><button type="submit">Ajouter un Artiste</button></a>
    <a href="{% url 'musiques:url_artistes' %}"><button type="submit">Tous les artistes</button></a>
    <a href="{% url 'musiques:url_base' %}"><button type="submit">Tous les morceaux</button></a>
  </nav>
  <hr>
  <main class="corps">
    <h3>Les artistes</h3>
      <section class="row">
        <div class="cont">
        {% for x in artistes %}
          <div class="affAut row col-lg-3">
            <p class="col-lg-12"> {{ x.id }}</p>
            <hr>
            <p class="col-lg-6"> Nom :</p>
            <p class="col-lg-6"> {{ x.nom }}</p>
            <a class="col-lg-6" href="http://localhost:8000/musiques/modifArtiste/{{ x.id }}"> <img src="../../static/img/edit.png" alt""></a>
            <a class="col-lg-6" href="http://localhost:8000/musiques/SupprArtiste/{{ x.id }}"> <img src="../../static/img/delete.png" alt""></a>
          </div>
        {% endfor %}
      </div>
    </section>
  </main>
</body>

musiques/templates/musiques/Base_View.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Django Musique</title>
    <link rel="stylesheet" href="../../static/css/bootstrap-theme.css">
    <link rel="stylesheet" href="../../static/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="../../static/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/css/index.css">
</head>
<body>
  <hr>
  <nav class="listeBoutons">
    <a href="{% url 'musiques:url_createM' %}"><button type="submit">Ajouter un Morceau</button></a>
    <a href="{% url 'musiques:url_createA' %}"><button type="submit">Ajouter un Artiste</button></a>
    <a href="{% url 'musiques:url_artistes' %}"><button type="submit">Tous les artistes</button></a>
    <a href="{% url 'musiques:url_base' %}"><button type="submit">Tous les morceaux</button></a>
  </nav>
  <hr>
  <main class="corps">
    <h3>Les morceaux</h3>
      <section class="row">
        <div class="cont">
        {% for x in morceaux %}
          <div class="affAut row col-lg-3">
            <p class="col-lg-12"> {{ x.id }}</p>
            <hr>
            <p class="col-lg-6"> Titre :</p>
            <p class="col-lg-6"> {{ x.titre }}</p>
            <p class="col-lg-6"> Date sortie : </p>
            <p class="col-lg-6"> {{ x.date_sortie }}</p>
            <p class="col-lg-6"> Artiste : </p>
            <p class="col-lg-6"> {{ x.clefE.nom }}</p>
            <a class="col-lg-6" href="http://localhost:8000/musiques/modifMorceau/{{ x.id }}"> <img src="../../static/img/edit.png" alt""></a>
            <a class="col-lg-6" href="http://localhost:8000/musiques/SupprMorceau/{{ x.id }}"> <img src="../../static/img/delete.png" alt""></a>
          </div>
        {% endfor %}
      </div>
    </section>
  </main>
</body>

musiques/templates/musiques/Modif.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Django Musique</title>
    <link rel="stylesheet" href="../../static/css/bootstrap-theme.css">
    <link rel="stylesheet" href="../../static/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="../../static/css/bootstrap.css">
    <link rel="stylesheet" href="../../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../static/css/index.css">
</head>
<body>
  <hr>
  <nav class="listeBoutons">
    <a href="{% url 'musiques:url_createM' %}"><button type="submit">Ajouter un Morceau</button></a>
    <a href="{% url 'musiques:url_createA' %}"><button type="submit">Ajouter un Artiste</button></a>
    <a href="{% url 'musiques:url_artistes' %}"><button type="submit">Tous les artistes</button></a>
    <a href="{% url 'musiques:url_base' %}"><button type="submit">Tous les morceaux</button></a>
  </nav>
  <hr>
  <main class="corps">
    <section>
      <h3>Modifier</h3>
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
      <input type="submit" value="Modifier" />
      </form>
    </section>

  </main>
</body>

musiques/templates/musiques/Suppr.html
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <title>Django Musique</title>
  <link rel="stylesheet" href="../../static/css/bootstrap-theme.css">
  <link rel="stylesheet" href="../../static/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="../../static/css/bootstrap.css">
  <link rel="stylesheet" href="../../static/css/bootstrap.min.css">
  <link rel="stylesheet" href="../../static/css/index.css">
</head>
<body>
  <hr>
  <nav class="listeBoutons">
    <a href="{% url 'musiques:url_createM' %}"><button type="submit">Ajouter un Morceau</button></a>
    <a href="{% url 'musiques:url_createA' %}"><button type="submit">Ajouter un Artiste</button></a>
    <a href="{% url 'musiques:url_artistes' %}"><button type="submit">Tous les artistes</button></a>
    <a href="{% url 'musiques:url_base' %}"><button type="submit">Tous les morceaux</button></a>
  </nav>
  <hr>
  <main class="suppr">
    <div class="filtre">
  <h1>Confirmer suppression ?</h1>
  <div class="affAut2 row">
    <p class="col-lg-12"> {{ donnees.id }}</p>
    <hr>
    <p class="col-lg-6"> titre :</p>
    <p class="col-lg-6"> {{ donnees.titre }}</p>
    <p class="col-lg-6"> date sortie : </p>
    <p class="col-lg-6"> {{ donnees.date_sortie }}</p>
    <p class="col-lg-6"> Artiste : </p>
    <p class="col-lg-6"> {{ donnees.clefE.nom }}</p>
    <form method="post" action="">
      {% csrf_token %}
      <button type="submit" value=""><img src='../../static/img/oui.png' alt''></button>
    </form>
    <a href="{% url 'musiques:url_base' %}"><button type="submit"><img src='../../static/img/non.png' alt''></button></a>
    </div>
</div>
</main>
</body>

musiques/templates/musiques/SupprA.html
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <title>Django Musique</title>
  <link rel="stylesheet" href="../../static/css/bootstrap-theme.css">
  <link rel="stylesheet" href="../../static/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="../../static/css/bootstrap.css">
  <link rel="stylesheet" href="../../static/css/bootstrap.min.css">
  <link rel="stylesheet" href="../../static/css/index.css">
</head>
<body>
  <hr>
  <nav class="listeBoutons">
    <a href="{% url 'musiques:url_createM' %}"><button type="submit">Ajouter un Morceau</button></a>
    <a href="{% url 'musiques:url_createA' %}"><button type="submit">Ajouter un Artiste</button></a>
    <a href="{% url 'musiques:url_artistes' %}"><button type="submit">Tous les artistes</button></a>
    <a href="{% url 'musiques:url_base' %}"><button type="submit">Tous les morceaux</button></a>
  </nav>
  <hr>
  <main class="suppr">
    <div class="filtre">
  <h1>Confirmer suppression ?</h1>
  <div class="affAut2 row">
    <p class="col-lg-6"> Id :</p>
    <p class="col-lg-6"> {{ donnees.id }}</p>
    <p class="col-lg-6"> Nom :</p>
    <p class="col-lg-6"> {{ donnees.nom }}</p>
    <form method="post" action="">
      {% csrf_token %}
      <button type="submit" value=""><img src='../../static/img/oui.png' alt''></button>
    </form>
    <a href="{% url 'musiques:url_base' %}"><button type="submit"><img src='../../static/img/non.png' alt''></button></a>
    </div>
</div>
</main>
</body>

musiques/templates/musiques/morceau_detail.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>Django Musique</title>
    <link rel="stylesheet" href="../static/css/bootstrap-theme.css">
    <link rel="stylesheet" href="../static/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="../static/css/bootstrap.css">
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/index.css">
</head>
<body>
  <div class="row">
  <h1 class="col-lg-3">{{ morceau.titre }}</h1>
  <p class="col-lg-3">{{ morceau.clefE.nom }}</p>
  <p class="col-lg-3">{{ morceau.date_sortie }}</p>
  </div>
</body>